s-espinosa/demonight

- Gemfile
- Gemfile.lock
- app/controllers/projects_controller.rb
- app/views/projects/new.html.erb
- spec/factories.rb
- spec/features/user_clicks_on_sign_up_spec.rb
- spec/rails_helper.rb
- spec/support/factory_girl.rb
* Add FactoryGirl and DatabaseCleaner
* Create factory for user
* Test to see if a user can visit the new project path
* Implement ability to visit the new project path
> 2 sign up button

- app/controllers/projects_controller.rb
- app/models/project.rb
- app/views/layouts/application.html.erb
- app/views/projects/new.html.erb
- app/views/projects/show.html.erb
- config/routes.rb
- db/migrate/20161126153426_create_projects.rb
- db/schema.rb
- spec/features/user_can_create_a_project_spec.rb
* Add test to verify that a logged in user can create a project
* Add form to create a new project
* Add routes to create and show a project
* Add create and show methods for project
* Add show view for project
* Add project to database
> 5 user can create project

- app/controllers/projects_controller.rb
- app/views/projects/index.html.erb
- spec/features/user_clicks_on_vote_spec.rb
* Add test for "Vote" link to project index
* Implement link to project index
> Create test and implementation to visit project index

- app/controllers/votes_controller.rb
- app/views/projects/index.html.erb
- app/views/votes/new.html.erb
- config/routes.rb
- spec/factories.rb
- spec/features/user_clicks_on_project_spec.rb
- spec/features/user_clicks_on_vote_spec.rb
* Create test
* Create factory
* Implement
* Fix voting test descriptions
> 4 links to vote page

- app/controllers/projects_controller.rb
- app/models/project.rb
- app/models/user.rb
- app/models/vote.rb
- spec/features/user_cannot_see_projects_with_votes_spec.rb
* Create test to verify that a user can only see projects they haven't voted on.
* Implement.
> 12 remove voted projects

- Gemfile
- Gemfile.lock
> Add 12 Factor Gem

- README.md
- app/controllers/admin/demo_nights_controller.rb
- config/sample_application.yml
* Updates README with additional detail.
* Creates `sample_application.yml` to ease use of Figaro.
* Removes whitespace from `demo_nights_controller.rb`.
> Update readme and add sample.yml

- app/models/demo_night.rb
- app/views/admin/dashboard/show.html.erb
- db/migrate/20161214215500_change_active_on_demo_nights.rb
- db/schema.rb
- spec/factories.rb
- spec/models/demo_night_spec.rb
- change `active` to `status`
- add `#active?` on demo_night
- all tests pass
> closes #27

- app/controllers/admin/demo_nights_controller.rb
- app/models/demo_night.rb
- app/views/admin/demo_nights/index.html.erb
- config/routes.rb
- spec/features/admin_cannot_create_more_than_one_active_demo_night_spec.rb
- adds before action on `DemoNightsController` to check for other demo nights that are not `closed`
- redirects to  admin demo night index if active demo night exists
- no link yet to deactivate yet, should I add that?
> [READY] closes #25

- app/controllers/projects_controller.rb
- app/views/projects/new.html.erb
- PR #29 needs to be merged first and check for merge conflicts.
- refactors to `DemoNight.current.projects.new`
- removes hidden field from projects#new
> 41 project new nesting - Ready to Merge!

- Gemfile
- Gemfile.lock
- app/models/vote.rb
- spec/features/admin_can_view_dashboard_spec.rb
- spec/models/vote_spec.rb
- spec/rails_helper.rb
- validates uniqueness of user id and project id on vote table
- changed score calculations on admin can view dashboard spec due to validations changing scores
> closes #28

- app/controllers/projects_controller.rb
- app/models/project.rb
- app/models/user.rb
- db/migrate/20161220145423_add_user_to_project.rb
- db/schema.rb
- spec/factories.rb
- spec/features/user_can_edit_project_spec.rb
- spec/features/user_can_only_vote_on_a_project_once_spec.rb
- spec/models/project_spec.rb
- spec/models/user_spec.rb
- separates voted projects from submitted projects
> closes #39 - Ready!

- app/controllers/application_controller.rb
- app/controllers/projects_controller.rb
- app/models/project.rb
- app/models/user.rb
- app/views/projects/_form.html.erb
- app/views/projects/edit.html.erb
- app/views/projects/index.html.erb
- config/routes.rb
- db/migrate/20161220145423_add_user_to_project.rb
- db/schema.rb
- spec/factories.rb
- spec/features/user_can_edit_project_spec.rb
- spec/features/user_can_only_vote_on_a_project_once_spec.rb
- spec/models/project_spec.rb
- spec/models/user_spec.rb
- allows user to edit their projects if demo night is still `accepting_submissions`
- uses helper_method to check for `current demo night status`, project being edited `id` vs. `current demo night id`, and `project owner`
- add model tests for user
- all tests pass
> 50 user edit project

- app/assets/stylesheets/styles.scss
- app/controllers/application_controller.rb
- app/controllers/projects_controller.rb
- app/controllers/sessions_controller.rb
- app/controllers/votes_controller.rb
- app/models/vote.rb
- app/views/admin/dashboard/_vote_talley.html.erb
- app/views/admin/dashboard/show.html.erb
- app/views/admin/demo_nights/index.html.erb
- app/views/admin/demo_nights/new.html.erb
- app/views/home/show.html.erb
- app/views/layouts/application.html.erb
- app/views/projects/_form.html.erb
- app/views/projects/edit.html.erb
- app/views/projects/new.html.erb
- app/views/sessions/new.html.erb
- app/views/shared/_navbar.html.erb
- app/views/votes/new.html.erb
- config/routes.rb
- spec/features/admin_can_view_dashboard_spec.rb
- spec/features/user_can_vote_spec.rb
> 36 more styling

- spec/features/user_can_only_vote_on_a_project_once_spec.rb
I thought all the tests passed until I repulled master.
-fixes user can only vote on a project once.
> hotfix for test

- app/controllers/votes_controller.rb
> Only allow access to voting screens if currently in voting mode

- app/views/admin/demo_nights/index.html.erb
Switches text to link. Closes #73.
> Update index to include link to current demo night

- Gemfile
- Gemfile.lock
- app/controllers/votes_controller.rb
- app/models/project.rb
- still kind of hacky. but it's marginally better because there's not raw SQL?
> fixes raw sql query

- app/models/project.rb
- app/views/admin/projects/index.html.erb
- app/views/projects/index.html.erb
@notmarkmiranda Thoughts? In practice we don't ever tell the student not to include themselves in the team, so I feel like this method was resulting in their name being displayed twice (i.e. my name was displayed twice when I was testing it because that's how I behaved).
> Remove  method and uses

- app/views/admin/demo_nights/index.html.erb
@notmarkmiranda Added a link. Quick fix. Let me know what you think.
> Add link to DemoNight show

- app/assets/stylesheets/styles.scss
- app/views/projects/_form.html.erb
- fixes so buttons are clickable on forms
- had to remove wave effect from new project form
- all tests pass (36)
> closes #82

- app/models/demo_night.rb
- app/models/project.rb
- app/views/admin/demo_nights/show.html.erb
- spec/features/admin_can_see_voted_projects_in_order_form_most_votes_to_least_spec.rb
- spec/models/demo_night_spec.rb
- spec/models/project_spec.rb
@s-espinosa @notmarkmiranda this pr:
-puts a project sorting method on demonight
-adds model testing for this method
-that is all
👍
> 85 ls admin sees projects in victory order

- app/models/project.rb
> Change average to float

- public/404.html
#92 Updates 404 to be a full HTML page.
> 92 Update 404

- app/controllers/projects_controller.rb
- app/views/projects/_form.html.erb
- spec/features/default/user_can_create_a_project_spec.rb
Adds a date of the DemoNight final so students can check their calendars.
> Add date to project form

- app/views/shared/_navbar.html.erb
- spec/features/admin/admin_can_login_spec.rb
* Changes nav button
* Updates tests
> Make new demo night button conditional on no current demo night

- app/controllers/admin/projects_controller.rb
- app/views/admin/demo_nights/_vote_talley.html.erb
- config/routes.rb
- spec/factories.rb
- spec/features/admin/admin_can_delete_projects_spec.rb
- Add delete functionality for admins
- Have confirmation on delete
- Add another selenium test! Woo!
- All tests pass: #40
- Test Coverage: 83%
@s-espinosa, @lsaville thoughts?
> 89 admin project destroy

- app/assets/javascripts/materializeFunctions.js
- app/controllers/admin/projects_controller.rb
- app/views/admin/demo_nights/_vote_talley.html.erb
- app/views/layouts/application.html.erb
- app/views/projects/edit.html.erb
- app/views/projects/new.html.erb
- app/views/votes/new.html.erb
- config/routes.rb
- spec/factories.rb
- spec/features/admin/admin_can_delete_projects_spec.rb
- Remove all jQuery from views and puts it in a separate script file
- Merge #89 first
- All tests pass: 40
- Test coverage: 83.5%
> 102 refactor jquery from views

- app/views/votes/new.html.erb
- add descriptions for voting categories
- remove labels
- All tests pass: 39
- Test coverage: 81.8%
@s-espinosa check it out!
> 111 voting category descriptions

- app/views/admin/demo_nights/new.html.erb
- app/views/votes/new.html.erb
- bug fix for button on demo night new
- @s-espinosa merge #111 first. thanks!
> 114 new demonight button bug

- app/views/admin/demo_nights/index.html.erb
- app/views/admin/demo_nights/new.html.erb
- app/views/votes/new.html.erb
- change styling on link to create new demo night to match rest of site
- merge #111 and #114 first @s-espinosa thanks!
> 117 create demo night button

- app/views/projects/index.html.erb
Closes #110 @notmarkmiranda Changes language in project index based on feedback from Nate. Let me know what you think!
> Closes #110 Change vote to rate in language in views

- spec/features/default/user_can_only_vote_on_a_project_once_spec.rb
- spec/features/default/user_can_vote_spec.rb
- spec/features/default/user_clicks_on_project_spec.rb
- spec/features/default/visitor_can_login_spec.rb
Changes "Vote" to "Rate" in feature specs to match current implementation.
> Update failing tests to use

- app/models/project.rb
- app/views/projects/index.html.erb
- spec/features/default/user_can_vote_spec.rb
@notmarkmiranda Thoughts? Believe this effectively scopes voting down to only M3 and M4 projects. Let me know if you see any other implications.
Thanks!
> 109 Scope projects for voting to only M3 and M4

- app/controllers/votes_controller.rb
- app/views/votes/new.html.erb
Since voting has been a problem word in the past, I tried to change them all to Rate. Since this doesn't technically need to be accepted until Thursday, I figured I'd open a PR instead of just deploying.
> Renamed votes to rates in public views

- Gemfile
- Gemfile.lock
- app/models/project.rb
@notmarkmiranda @neight-allen
Closes #132 Quick update to round the voting results. Thoughts? Think we can merge if this looks good to you.
> Round voting results and add awesome_print

- app/models/project.rb
@notmarkmiranda Adjust to round to three decimals to make the ratings more precise.
Connected to #132
> Make rounding calculation more precise

- config/environments/development.rb
@notmarkmiranda Adds line to config to allow Redis requests on local host.
> Update development config to run redis locally

- app/models/demo_night.rb
- app/views/admin/demo_nights/_demo_night.html.erb
- app/views/admin/demo_nights/index.html.erb
- app/views/admin/demo_nights/show.html.erb
- config/cable.yml
- config/environments/production.rb
- spec/features/admin/admin_can_create_demo_night_spec.rb
- spec/features/admin/admin_can_login_spec.rb
- spec/features/admin/admin_can_view_demo_index_spec.rb
- spec/features/admin/admin_can_view_demo_night_spec.rb
- spec/features/admin/admin_cannot_activate_more_than_one_demo_night_spec.rb
- spec/features/admin/admin_cannot_create_more_than_one_active_demo_night_spec.rb
- Add project count to `demo_night.rb`
- Refactor demo night cards to a partial
- Humanize all tests
- All tests pass: 42
- Test coverage: 80.07%
@s-espinosa let me know what you think.
> 130 - Add Project Count

- app/views/admin/scoreboard/_projects.html.erb
- app/views/admin/scoreboard/show.html.erb
- Removes top 5 bug from live scoreboard to show all projects in ranked order
- All tests pass: 42
- Test coverage: 80%
> closes #155

- app/models/vote.rb
- fixes action cable refreshing to only 5 projects after commit of a new vote.
- all tests pass: 44
- test coverage: 79%
> closes #160

- app/views/admin/demo_nights/_demo_night.html.erb
@notmarkmiranda 
- Adds links to admin DemoNight index to see individual show pages
- all tests pass: 44
- test coverage: 79.72%
> Create links from admin demonight index to show pages

- app/views/shared/_navbar.html.erb
Closes #159 
@notmarkmiranda 
Adds conditional to check to see if a `current_user` exists before displaying the Log Out button. Tests pass.
> Remove log out when not logged in

- app/controllers/admin/projects_controller.rb
- app/controllers/projects_controller.rb
@notmarkmiranda Can you take a quick look.
Intent is to stop accepting submissions if we have 16 projects for a current demo night, and to open it back up to accepting submissions if it dips below 16.
Perhaps in the future we could generate a waiting list?
> Add project limiting

- config/environments/production.rb
Update URL to Turing subdomain in project.
> Update URL for ActionCable

- README.md
- app/controllers/admin/demo_nights_controller.rb
- app/controllers/admin/scoreboard_controller.rb
- app/controllers/projects_controller.rb
- app/controllers/votes_controller.rb
- app/views/admin/demo_nights/index.html.erb
- app/views/admin/demo_nights/new.html.erb
- app/views/admin/projects/show.html.erb
- app/views/home/no_demo_night.html.erb
- app/views/projects/index.html.erb
- app/views/shared/_mobile_nav_items.html.erb
- app/views/shared/_navbar.html.erb
- spec/features/admin/admin_can_archive_a_demo_night_spec.rb
- spec/features/admin/admin_can_create_demo_night_spec.rb
- spec/features/admin/admin_can_delete_projects_spec.rb
- spec/features/admin/admin_can_edit_a_project_spec.rb
- spec/features/admin/admin_can_login_spec.rb
- spec/features/admin/admin_can_update_demo_night_status_spec.rb
- spec/features/admin/admin_can_view_demo_index_spec.rb
- spec/features/admin/admin_can_view_demo_night_spec.rb
- spec/features/admin/admin_cannot_activate_more_than_one_demo_night_spec.rb
- spec/features/admin/admin_cannot_create_more_than_one_active_demo_night_spec.rb
- spec/features/default/user_can_edit_project_spec.rb
- spec/features/default/visitor_can_login_spec.rb
Change copy to reflect new name.
> Change name to code fair

- app/controllers/admin/projects_controller.rb
- app/controllers/projects_controller.rb
Update max number of signups to 12.
> Update highest count of projects

- Gemfile
- Gemfile.lock
> Add Ruby version to Gemfile

- app/views/layouts/application.html.erb
* Updated the app name in the header so that correct name was reflected in tabs, etc.
> Update app name in header

- Gemfile
- Gemfile.lock
- spec/factories.rb
- spec/support/factory_bot.rb
* Switch to reflect ThoughtBot's updated name.
> Switch from FactoryGirl to FactoryBot

- spec/features/default/user_can_vote_spec.rb
* Update test that would sometimes fail because of JS/Selenium testing with a browser.
> Update inconsistent test

- app/controllers/admin/projects_controller.rb
- app/controllers/application_controller.rb
- app/controllers/projects_controller.rb
* Refactor lists of modules in ProjectsController and Admin::ProjectsController into method in ApplicationController.
* Add "Mod 4 Cross Poll" to list of modules.
> Add cross poll and refactor modules into method

- app/models/project.rb
Make cross-poll projects votable.
> Add cross poll to list of projects to vote
